name: release

on:
  push:
    tags:
      - v*
jobs:

  build-linux-cp38:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64

    steps:
    - uses: actions/checkout@v2

    - name: Install Python package dependencies
      run: /opt/python/cp38-cp38m/bin/python -m pip install cython numpy

    - name: Build binary wheel
      run: /opt/python/cp38-cp38m/bin/python setup.py build_ext --inplace
